/*
 * PluginsSetup.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nuchina.tools;

import javax.swing.JOptionPane;

/**
 * 
 * @author __USER__
 */
public class PluginsSetup extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6782291617890537731L;

	/** Creates new form PluginsSetup */
	public PluginsSetup() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		path = new javax.swing.JTextField();
		btn = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		message = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Eclipse\u63d2\u4ef6\u5b89\u88c5\u2014\u2014\u4f5c\u8005\uff1aCalcYu");

		btn.setText("\u751f\u6210");
		btn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnActionPerformed(evt);
			}
		});

		message.setColumns(20);
		message.setRows(5);
		jScrollPane1.setViewportView(message);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addComponent(
																		path,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		579,
																		Short.MAX_VALUE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		btn))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		666,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btn)
												.addComponent(
														path,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										233, Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
		//GEN-END:initComponents

	private void btnActionPerformed(java.awt.event.ActionEvent evt) {
		if ("".equals(this.path.getText().trim())) {
			JOptionPane.showMessageDialog(this, "请输入Eclipse插件地址！");
		} else {
			PluginConfigCreator creator = new PluginConfigCreator();
			String msg = creator.print(this.path.getText().trim());
			if ("".equals(msg)) {
				JOptionPane.showMessageDialog(this, "请检查插件地址是否正确！");
			} else {
				this.message.setText(msg);
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PluginsSetup().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea message;
	private javax.swing.JTextField path;
	// End of variables declaration//GEN-END:variables

}